### ISSUE TITLE
En Aptana con python2.7  ImportError: No module named

### ISSUE THREAD

**Issue by lexygalban** [ybenitezf/miner#1]
El codigo esta bien y funciona bien en linux pero lo estoy probando en Windows con Aptana y me ocurre esto.....

Traceback (most recent call last):
  File "C:\Users\Lex\My Documents\Aptana Studio 3 Workspace\miner\src\miner.py", line 7, in <module>
    from  parser.logParser import Parser, LogObserverPlugin
ImportError: No module named logParser

Al parecer no encuentra el modulo logParser que esta en el paquete parser.
La linea donde da el error tiene esto: "from  parser.logParser import Parser, LogObserverPlugin"
Creo que no encuentra el paquete parser porque se esta equivocando con el "parser.logParser" y en vez de buscar en un paquete esta buscando en otro modulo, probé cambiar el nombre del paquete parser y entonces ejecuto el script pero al cambiar ese paquete pues no cargó ningun plugin es por eso que creo que  existe algo que el aptana se queda loco al buscar el "parser.logParser"

**Comment by ybenitezf** [comment]
La verdad nunca probé el código en Windows, nunca fue mi objetivo que funcionara en ese sistema. De todas formas posiblemente el error sea en la forma en que se ejecuta el sistema dentro de Aptana, en ese IDE debe configurarse de alguna manera el ambiente de ejecución del sistema.

En la concreta, se diseño para que funcionara en Linux no en Windows.

**Comment by ybenitezf** [comment]
Creo que puedes aplicar 3 variantes para resolver este problema:
1. Instalas Linux en una maquina virtual y trabajas y pruebas el sistema ahí.
2. Te instalas Linux en un partición y trabajas sobre eso, `Aptana`  funciona de la misma manera en ambos sistema así que es probable que te de el mismo error.
3. Buscar la forma de configurar el ambiente de ejecución para el proyecto en `Aptana`.
